---

- name: Install sensu_agent
  pkgng:
    name: "{{ sensu_agent_package }}"
    state: present

- name: Create sensu_agent_group
  group:
    name: "{{ sensu_agent_group }}"
    state: present

- name: Create sensu_agent_user
  user:
    name: "{{ sensu_agent_user }}"
    group: "{{ sensu_agent_group }}"
    state: present

- name: Create rc.subr
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ sensu_agent_service | regex_replace('-', '_') }}"
    validate: sh -n %s
  notify:
    - Restart sensu_agent

- name: Enable sensu_agent_service
  service:
    name: "{{ sensu_agent_service }}"
    enabled: yes
